version: "3.9"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: taskify
      POSTGRES_USER: taskify
      POSTGRES_PASSWORD: taskify
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
